# ================================
# Cloud Build 配置
# 用于自动构建和部署到 Cloud Run
# ================================

steps:
  # 步骤 1: 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:latest'
      - '--cache-from'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:latest'
      - '.'

  # 步骤 2: 推送带 commit SHA 标签的镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:$COMMIT_SHA'

  # 步骤 3: 推送 latest 标签的镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:latest'

  # 步骤 4: 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'note-app'
      - '--image=asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:$COMMIT_SHA'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'

# 保存构建的镜像
images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:$COMMIT_SHA'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/note-app/web:latest'

# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# 超时设置 (20 分钟)
timeout: '1200s'

# 替换变量
substitutions:
  _REGION: 'asia-east1'
  _SERVICE_NAME: 'note-app'
